<x-guest-layout>
    <div class="w-full bg-white">
        <x-sub-page-hero icon="terms" subtitle="" title="Terms and Conditions"></x-sub-page-hero>
        <x-container class="py-14">
            <div class="relative">
                <h4 class="text-2xl font-bold">{{ __('User Agreement') }}</h4>
                <p class="font-semibold text-lg my-4">{{  __('For the purposes of these Terms and Conditions:') }}</p>
    
                @php
                    $terms = [
                        [ 'category' => 'Affiliate', 'content' => 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority' ],
                        [ 'category' => 'Account', 'content' => 'means a unique account created for You to access our Service or parts of our Service.rity' ],
                        [ 'category' => 'Company', 'content' => 'refers to myCrypto Tax' ],
                        [ 'category' => 'Country', 'content' => 'refers to Ukraine' ],
                        [ 'category' => 'Content', 'content' => 'refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content.' ],
                        [ 'category' => 'Device', 'content' => ' means any device that can access the Service such as a computer, a cellphone or a digital tablet.' ],
                        [ 'category' => 'Feedback', 'content' => 'means feedback, innovations or suggestions sent by You regarding the attributes, performance or features of our Service' ],
                        [ 'category' => 'Products', 'content' => 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority' ],
                        [ 'category' => 'Orders', 'content' => 'mean a request by You to purchase Products from Us' ],
                        [ 'category' => 'Promotions', 'content' => 'refer to contests, sweepstakes or other promotions offered through the Service' ],
                        [ 'category' => 'Service', 'content' => 'refers to the Website' ],
                        [ 'category' => 'Terms and Conditions', 'content' => '(also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by TermsFeed Terms and Conditions Generator' ],
                        [ 'category' => 'Third-party Social Media Service', 'content' => 'means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service' ],
                        [ 'category' => 'Website', 'content' => 'refers to [mycrypto Tax],  accessible from https://mycrypto.tax' ],
                        [ 'category' => 'You', 'content' => ' means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' ],
                    ]
                @endphp
                
                @foreach ($terms as $term)
                    <div class="flex cl items-start py-3">
                        <div class="w-4 h-4 mr-3">
                            <x-icon name="square-dot" class="w-4 h-4 mt-1"/>
                        </div>
                        <p><span class="font-semibold">{{ __( $term['category'] ) }}</span>: {{ __( $term['content'] ) }}</p>
                    </div>
                @endforeach
    
                <p class="font-semibold text-lg my-4">{{  __('Acknowledgment') }}</p>
                <p class="py-2">{{ __('These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service') }}</p>
                <p class="py-2">{{ __('Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and  onditions apply to all visitors, users and others who access or use the Service. By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.') }}</p>
                <p class="py-2">{{ __('You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service. Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service') }}</p>
            </div>
        </x-container>
        <x-footer-get-start/>
    </div>
    <x-footer></x-footer>
</x-guest-layout>